#!/usr/bin/env python3
"""Attorney audit companion: a decision record → reviewable Markdown.

The companion walks the rendered document component by component and answers,
for each one, the question an attorney otherwise has to guess at: WHY is this
clause here — which rule selected it, which facts that rule read, where each
fact came from (attorney determination / client file / manifest / derived),
and what statutory authority the language carries. Components that were
considered and NOT included are listed with the same detail, because an
omission is a decision too.

    python3 engine/assemble.py --manifest M --slots S.json --audit review.md
"""
from __future__ import annotations

import choices as _choices

SOURCE_LABEL = {
    "attorney_determination": "ATTORNEY DETERMINATION",
    "client_intake": "client intake",
    "document_extraction": "document extraction",
    "slots_file": "slots file",
    "manifest_pin": "manifest pin",
    "manifest_default": "manifest default",
    "derived": "derived",
    "unknown": "unknown",
}

# attorney-asserted facts sort to the top of the ledger; defaults to the bottom
_SOURCE_ORDER = {"attorney_determination": 0, "client_intake": 1,
                 "document_extraction": 2, "slots_file": 3, "manifest_pin": 4,
                 "manifest_default": 5, "derived": 6, "unknown": 7}


def _val(v, limit=70) -> str:
    if isinstance(v, bool):
        return "yes" if v else "no"
    if v is None:
        return "—"
    s = str(v).replace("\n", " ")
    return s if len(s) <= limit else s[:limit - 1] + "…"


def _facts_inline(facts_considered: dict, facts: dict) -> str:
    parts = []
    for k, v in facts_considered.items():
        src = (facts.get(k) or {}).get("source", "unknown")
        if v is None and k not in facts:
            parts.append(f"`{k}` unset")
        else:
            parts.append(f"`{k}` = {_val(v, 40)} ({SOURCE_LABEL.get(src, src)})")
    return "; ".join(parts) if parts else "—"


def _why(d: dict, facts: dict) -> str:
    mode, kind = d.get("mode"), d.get("kind")
    if kind == "chrome" and d.get("included"):
        return "structural chrome (repo-authored scaffolding, not clause language)"
    if not d.get("included"):
        if mode == "add":
            return (f"condition `{d.get('when')}` not met — "
                    f"{_facts_inline(d.get('facts_considered', {}), facts)}")
        if mode == "remove":
            return (f"removal condition `{d.get('when')}` met — "
                    f"{_facts_inline(d.get('facts_considered', {}), facts)}")
        return d.get("note", "")
    if mode == "required":
        return "required by the template for every instrument of this type"
    if mode == "add":
        return (f"included because `{d.get('when')}` is satisfied — "
                f"{_facts_inline(d.get('facts_considered', {}), facts)}")
    if mode == "remove":
        return "present by default (no removal condition met)"
    if mode == "substitute":
        return "substitute-eligible (see text source below)"
    return d.get("note", "")


def record_to_markdown(record: dict, stamp: str | None = None) -> str:
    facts = record.get("facts", {})
    out = [f"# Audit Companion — {record.get('title') or record.get('template_id')}",
           "",
           f"**Template:** `{record.get('template_id')}` "
           f"({record.get('practice_area')}/{record.get('document_type')}) · "
           f"**Manifest:** `{record.get('manifest')}` · "
           f"**Decision-record schema:** v{record.get('_schema_version')}"
           + (f" · **Generated:** {stamp}" if stamp else ""),
           "",
           "> DRAFT GENERATED BY A TEMPLATE ENGINE — NOT LEGAL ADVICE. Every component",
           "> below states the rule that selected it, the facts that rule read, and each",
           "> fact's source, so the selection can be validated rather than guessed at.",
           "> An attorney must confirm each determination before this document is used.",
           ""]

    # NOTE: record["statutory_basis"] (the manifest's instrument-wide statutory
    # grounding) is deliberately NOT rendered here as a blanket section: on
    # branched families it mixes branch-specific authority (e.g. the lien
    # family's mechanics §§ 3255/3261 deadlines, which must never reach an
    # hoa_assessment audit). Branch-correct authority reaches the companion via
    # each block's Authority line and the applies_when-gated section 5 instead;
    # the record still carries the full map for downstream consumers.
    # hard statutory deadlines the document itself cannot satisfy (recording
    # windows, service clocks) — repeated in § 4 as attorney action items
    for n in record.get("deadline_notes") or []:
        out.append(f"> **⚠ STATUTORY DEADLINE** — {n}")
        out.append("")

    # --- 1. fact ledger ---------------------------------------------------
    out += ["## 1. Fact ledger", "",
            "| Fact | Value | Source | Detail |",
            "|---|---|---|---|"]
    for k in sorted(facts, key=lambda k: (_SOURCE_ORDER.get(facts[k].get("source"), 9), k)):
        e = facts[k]
        detail_bits = [e[x] for x in ("author", "date", "document", "basis", "detail")
                       if e.get(x)]
        out.append(f"| `{k}` | {_val(e.get('value'))} | "
                   f"{SOURCE_LABEL.get(e.get('source'), e.get('source'))} | "
                   f"{_val('; '.join(str(b) for b in detail_bits), 90)} |")
    out.append("")

    # --- 2. family discriminators ----------------------------------------
    disc = record.get("discriminators") or {}
    if disc:
        out += ["## 2. Family discriminators", ""]
        for s, spec in disc.items():
            if spec.get("pin") is not None:
                how = f"pinned to `{spec['pin']}` by this manifest"
            elif spec.get("required"):
                how = ("required — a missing or invalid value fails the render "
                       "instead of defaulting")
            else:
                how = ("optional — validated against the allowed values when "
                       "set (an invalid value fails the render)")
            out.append(f"- `{s}` = **{_val(spec.get('value'))}** — {how}. "
                       f"Allowed: {', '.join(f'`{e}`' for e in spec.get('enum') or [])}.")
        out.append("")

    # --- 2a. hard-fail constraints that were enforced -----------------------
    cons = record.get("constraints") or []
    if cons:
        out += ["**Hard-fail constraints enforced** (a violated constraint kills "
                "the render — this document passed all of them):", ""]
        for c in cons:
            status = ("checked and satisfied" if c.get("applied")
                      else f"not applicable (guard `{c.get('when')}` not met)")
            req = f" — required: `{c['require']}`" if c.get("require") else ""
            out.append(f"- `{c.get('id')}`: {status}{req}")
        out.append("")

    # --- 3. component decisions ------------------------------------------
    out += ["## 3. Component decisions", ""]
    n = 0
    for d in record.get("decisions", []):
        mark = "✔" if d.get("included") else "✘"
        head = d.get("block_id")
        if d.get("function"):
            head += f" · {d['function']}"
        n += 1
        out.append(f"### {n}. {mark} `{head}`"
                   + ("" if d.get("included") else " — NOT INCLUDED"))
        out.append("")
        out.append(f"- **Decision:** {_why(d, facts)}")
        if d.get("statutory_citation"):
            out.append(f"- **Authority:** {d['statutory_citation']}")
        if d.get("corpus_frequency"):
            out.append(f"- **Corpus support:** appears in {d['corpus_frequency']} "
                       f"firm documents of this family")
        if d.get("included") and d.get("kind") == "block":
            ts = d.get("text_source")
            out.append("- **Text source:** dominant partial (attorney-tested "
                       "library language)" if ts == "dominant"
                       else f"- **Text source:** variant `{ts}`")
        for v in d.get("variant_select") or []:
            if v.get("error"):
                out.append(f"- **Variant rule error:** {v['error']}")
            elif v.get("applied"):
                out.append(f"- **Variant applied:** `{v['variant']}` because "
                           f"`{v['when']}` — trigger: {_val(v.get('trigger'), 120)}")
            else:
                out.append(f"- **Variant considered, not applied:** `{v['variant']}` "
                           f"(`{v['when']}` → {_val(v.get('result'))})")
        slots = d.get("slots") or []
        if slots:
            filled = [s["name"] for s in slots if s["status"] == "filled"]
            markers = [s["name"] for s in slots if s["status"] == "marker"]
            omitted = [s["name"] for s in slots if s["status"] == "omitted"]
            bits = []
            if filled:
                bits.append("filled: " + ", ".join(f"`{x}`" for x in filled))
            if markers:
                bits.append("**NEEDS VALUE**: " + ", ".join(f"`{x}`" for x in markers))
            if omitted:
                bits.append("optional, unset (clause text omitted): "
                            + ", ".join(f"`{x}`" for x in omitted))
            out.append("- **Slots:** " + " · ".join(bits))
        if d.get("kind") in ("gap", "error"):
            out.append(f"- **⚠ {d['kind'].upper()}:** {d.get('note')}")
        if d.get("included") and d.get("rendered"):
            out.append("")
            out += ["> " + ln if ln.strip() else ">"
                    for ln in d["rendered"].splitlines()]
        out.append("")

    # --- 4. requires attorney action ---------------------------------------
    actions = []
    for n in record.get("deadline_notes") or []:
        actions.append(f"**⚠ STATUTORY DEADLINE** — {n}")
    for m in record.get("unfilled_markers", []):
        actions.append(f"Supply a value for `{m}` (rendered as a [[ marker ]] "
                       f"in the draft).")
    for d in record.get("decisions", []):
        if d.get("kind") == "gap":
            actions.append(f"`{d['block_id']}`: {d.get('note')} — language must "
                           f"be authored, never invented.")
        if d.get("kind") == "error":
            actions.append(f"`{d['block_id']}`: {d.get('note')}")
    for w in record.get("warnings", []):
        actions.append(f"Variant PII warning: {w}")
    out += ["## 4. Requires attorney action", ""]
    if actions:
        out += [f"- [ ] {a}" for a in actions]
    else:
        out.append("- [ ] Confirm the fact ledger and each component decision "
                   "above; no unfilled markers or gaps were detected.")
    if record.get("unset_optional_flags"):
        out += ["",
                "Optional flags left unset (their clause text was omitted, which "
                "may be intended): "
                + ", ".join(f"`{f}`" for f in record["unset_optional_flags"])]
    if record.get("paired_forms"):
        out += ["", "**Paired official forms:** "
                + ", ".join(record["paired_forms"])]

    # --- 5. paired requirements & statutory deadlines -----------------------
    # The manifest's structured checklist metadata (docs/PAIRED_REQUIREMENTS.md),
    # filtered to this matter. assemble_record() evaluates each entry's
    # `applies_when` guard against the matter facts into an `applicable` flag
    # (unevaluable fails safe to applicable — fail visible, never silent);
    # records that predate the flag are re-evaluated here against the fact
    # ledger with the same fail-visible bias. Falsy guard = entry omitted
    # (e.g. FM-050 on a childless divorce, § 3255 on an hoa_assessment lien).
    fact_vals = {k: (facts.get(k) or {}).get("value") for k in facts}
    applicable = []
    for r in record.get("paired_requirements") or []:
        if "applicable" in r:
            if not r["applicable"]:
                continue
        elif r.get("applies_when"):
            try:
                if not _choices.safe_eval(r["applies_when"], fact_vals):
                    continue
            except Exception:
                pass
        applicable.append(r)
    if applicable:
        out += ["", "## 5. Paired requirements & statutory deadlines", "",
                "> Companion documents and follow-through duties this instrument",
                "> carries. CALENDAR EVERY DEADLINE — several are penalty-bearing",
                "> or lien-fatal.", ""]
        for r in applicable:
            sev = (r.get("severity") or "info").upper()
            head = f"- [ ] **[{sev}]** {r.get('label', r.get('requirement_id'))}"
            detail = []
            if r.get("kind") == "companion_template" and r.get("companion_template_id"):
                detail.append(f"companion template `{r['companion_template_id']}`")
            if r.get("official_form_id"):
                detail.append(f"official form {r['official_form_id']}")
            if r.get("timing"):
                detail.append(f"timing: {r['timing']}")
            if r.get("disposition"):
                detail.append(f"disposition: {r['disposition']}")
            if detail:
                head += " (" + "; ".join(detail) + ")"
            out.append(head)
            if r.get("notes"):
                out.append(f"  - {r['notes']}")
            if r.get("citations"):
                out.append("  - Authority: " + "; ".join(r["citations"]))
    out.append("")
    return "\n".join(out)
