#!/usr/bin/env python3
"""Generate GAPS.md — what the template library is missing or what newly needs adding.

Cross-references four sources:
  1. Coverage  — corpus document types (schema/corpus_doctype_distribution.json) vs.
     the document types the manifests actually template (per practice area).
  2. Missing clauses — every GAP_* ref across all manifests, rolled up (these are
     library clauses that don't yet exist; seeded by clause_library/GAP_BACKLOG.md).
  3. Form pairings — me_forms_registry forms not yet wired into any manifest.
  4. Newly-required / changed law — the citation review queue (authority.jsonl), esp.
     regulatory changes (CTA/BOI), repeals (RULONA notarial, anatomical gift), and
     section renumberings that mean a clause's content/cite must be updated.
"""
from __future__ import annotations

import json
import os
import re
from collections import defaultdict
from pathlib import Path

from template_forge.engine import paths as _pack

PACK = _pack.pack_root()
MANIFESTS = PACK / "manifests"
CORPUS = (PACK / "schema") / "corpus_doctype_distribution.json"
AUTH = (PACK / "citations") / "authority.jsonl"
FORMS = Path(os.environ.get("TEMPLATE_FORGE_CLAUSE_DIR", "./clause_library")) / "forms_registry.jsonl"
OUT = Path("GAPS.md")

# Corpus doc types that are NOT drafted artifacts (court-issued or internal) — out of
# scope for a drafting-template library, so their absence is expected, not a gap.
NON_DRAFTING = {"order", "judgment", "memo", "correspondence", "other"}

# The shared me_forms_registry.jsonl predates the 2026-06 adversarial audit and
# carries form ids that do not exist on the current MJB list (F-FAM11): its
# "FM-070 Complaint for Divorce" is really FM-004 (FM-070 is Motion to Enforce),
# "FM-150 Child Support Affidavit" is FM-050, "FED-1" is CV-007 (Residential FED
# Complaint; the court-issued summons is CV-034), and "ME-RETT-1" is the Maine
# Revenue Services Form RETTD. The registry lives in the shared clause library,
# so it is corrected HERE (id translation) rather than mutated in place — a
# manifest pairing the verified current id counts as wiring the registry form.
FORM_ID_CURRENT = {
    "FM-070": "FM-004",
    "FM-150": "FM-050",
    "FED-1": "CV-007",
    "ME-RETT-1": "Form RETTD",
}


def load_manifests():
    mans = [json.loads(p.read_text()) for p in sorted(MANIFESTS.glob("*.json"))]
    return mans


def main():
    mans = load_manifests()
    corpus = {k: v for k, v in json.loads(CORPUS.read_text()).items() if not k.startswith("_")}
    forms = [json.loads(l) for l in FORMS.read_text().splitlines() if l.strip()]
    auth = [json.loads(l) for l in AUTH.read_text().splitlines() if l.strip()]

    # covered practice areas + a loose doc-type coverage map
    covered_pa = defaultdict(set)
    gap_refs = defaultdict(list)   # GAP_id -> [template_ids]
    paired = set()
    for m in mans:
        covered_pa[m["practice_area"]].add(m["document_type"])
        for f in m.get("paired_forms", []):
            paired.add(f)
            # paired_forms follow the "CODE (description)" convention, so a registry
            # form counts as paired when its form_id is the part before the
            # parenthetical (ids may be multi-word, e.g. "Form RETTD").
            code = f.split(" (")[0].strip()
            if code:
                paired.add(code)
        for ref in m.get("blocks", []):
            bid = ref.get("block_id", "")
            if bid.startswith("GAP_"):
                gap_refs[bid].append(m["template_id"])

    L = ["# GAPS — template coverage & freshness backlog\n",
         f"Generated by `tools/gap_report.py`. {len(mans)} templates, "
         f"{len(gap_refs)} distinct missing-clause gaps.\n"]

    # 1. Coverage
    L.append("## 1. Document-type coverage\n")
    L.append("Per practice area: corpus drafting doc types (count ≥ 8) vs. templated. "
             "Court-issued (`order`,`judgment`) and internal (`memo`,`correspondence`,`other`) "
             "types are out of scope for a drafting library.\n")
    for pa in sorted(corpus):
        drafting = {dt: n for dt, n in corpus[pa].items() if dt not in NON_DRAFTING}
        ntmpl = len(covered_pa.get(pa, set()))
        L.append(f"- **{pa}** — {ntmpl} templates; corpus drafting types: "
                 + ", ".join(f"{dt}({n})" for dt, n in sorted(drafting.items(),
                             key=lambda x: -x[1])))
        # crude per-type coverage hint
        uncovered = [dt for dt in drafting if not any(
            dt in t or t in dt or _alias(dt, t) for t in covered_pa.get(pa, set()))]
        if uncovered:
            L.append(f"  - not obviously covered: {', '.join(uncovered)} "
                     f"(may be served by a differently-named template — verify)")

    # 2. Missing clauses (GAP refs)
    L.append("\n## 2. Missing clause language (GAP refs to author)\n")
    L.append("Each is a clause the templates need but your clause library does not yet "
             "contain. Scaffolded as a visible `[GAP:]` marker; author from statute or "
             "re-mine a wider corpus (see clause_library/GAP_BACKLOG.md).\n")
    for gid in sorted(gap_refs):
        tmpls = ", ".join(sorted(set(gap_refs[gid])))
        L.append(f"- `{gid}` — needed by: {tmpls}")

    # 3. Form pairings
    L.append("\n## 3. Official Maine forms not yet paired\n")
    unpaired = [f for f in forms
                if FORM_ID_CURRENT.get(f["form_id"], f["form_id"]) not in paired]
    L.append(f"{len(forms) - len(unpaired)} of {len(forms)} registry forms are wired "
             "into a template. Unpaired forms (consider adding a template or a "
             "paired_forms ref):\n")
    for f in unpaired:
        fid = FORM_ID_CURRENT.get(f["form_id"], f["form_id"])
        L.append(f"- **{fid}** {f['title']} — {', '.join(f.get('matter_types', []))}")

    # 4. Newly-required / changed law
    L.append("\n## 4. Newly-required / changed law (from citation review queue)\n")
    L.append("Items where the law changed after the corpus was authored, so a clause's "
             "content (not just its cite) needs updating or adding. Full detail + sources "
             "in `citations/CITATION_AUDIT.md`.\n")
    changed = [r for r in auth if r["status"] == "changed"]
    repealed = [r for r in auth if r["status"] == "repealed"]
    renum = [r for r in auth if r["status"] in ("superseded", "uncertain")
             and r.get("current_form") and _section_changed(r)]
    def uniq(rows):
        seen, out = set(), []
        for r in rows:
            key = _theme(r)
            if key in seen:
                continue
            seen.add(key); out.append(r)
        return out
    L.append("### Regulatory change — content out of date (ADD/REWRITE)")
    for r in uniq(changed):
        L.append(f"- **{r['citation']}** → {r['current_form']}")
        L.append(f"  - affects blocks {', '.join(r['blocks'])}; {(r['note'] or '')[:200]}")
    L.append("\n### Repealed / replaced statutes (RE-CITE)")
    for r in uniq(repealed):
        L.append(f"- **{r['citation']}** → {r['current_form']}  _(blocks: {', '.join(r['blocks'])})_")
    L.append("\n### Section renumbered — verify content & re-cite")
    for r in uniq(renum):
        L.append(f"- **{r['citation']}** → {r['current_form']}  _(blocks: {', '.join(r['blocks'])})_")

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")
    print(f"  templates={len(mans)}  missing-clause gaps={len(gap_refs)}  "
          f"unpaired forms={len(unpaired)}  changed-law={len(changed)}  "
          f"repealed={len(set(_theme(r) for r in repealed))}")


def _alias(dt, t):
    A = {"deed": ("warranty_deed", "quitclaim_deed", "pr_deed"),
         "agreement": ("purchase_sale_agreement", "operating_agreement",
                       "shareholder_agreement", "marital"),
         "other": ("will", "power_of_attorney", "advance_directive", "trust"),
         "letter": ("cover_letter", "demand_letter", "engagement_letter", "discovery_letter")}
    return any(t == a or t.endswith(a) for a in A.get(dt, ()))


def _section_changed(r):
    s = re.search(r"§+\s*([\d-]+)", r["citation"])
    c = re.search(r"§+\s*([\d-]+)", r.get("current_form") or "")
    return bool(s and c and s.group(1) != c.group(1))


def _theme(r):
    return re.sub(r"\s*\([^)]*\)", "", r["citation"]).strip()


if __name__ == "__main__":
    main()
